version: "3.8"
services:
  mongodb:
    container_name: sweetdreams-db
    image : mongo
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped